
###

POST http://localhost:3000/auth/api/login
Content-Type: application/json

{
    "email": "yashsharma@gmail.com",
    "password": "yash@123"
}

###

POST http://localhost:3000/auth/api/register
Content-Type: application/json

{
    "email": "yash.dev@gmail.com",
    "password": "yash@123"
}

